services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.3
    # restart: always
    ports:
      - "8090:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - shared_network

volumes:
  evolution_instances:

networks:
  shared_network:
    external: true
