apiVersion: v1
kind: Pod
metadata:
  name: busybox-never
  labels:
    name: busybox-never
spec: 
  restartPolicy: Never
  containers:
    - name: busybox-never
      image: nginx:latest
      command: ["sh", "-c", " echo Ejemplo de pod fallado && exit 1"]
  