version: "3.8"
services:
  db:
    image: container-registry.oracle.com/database/free
    container_name: oracle
    # restart: always
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: Tobirama19++
    volumes:
      - local_oracle:/opt/oracle/oradata

volumes:
  local_oracle: