version: "3.8"
services:
  db:
    # image: postgres:16
    build:
      context: .
      dockerfile: dockerfile
    container_name: postgress
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rmartel
      POSTGRES_PASSWORD: Tobirama19++
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    networks:
      - postgres_red
  pgadmin:
    image: dpage/pgadmin4:8.10
    container_name: pgadmin
    # restart: always
    ports:
      - "8089:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rmartel@local.com
      PGADMIN_DEFAULT_PASSWORD: Tobirama19++
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgres_red

networks:
  postgres_red:
    driver: bridge

volumes:
  local_pgdata:
  pgadmin-data: