version: "3.8"

services:
  awx_postgres:
    image: postgres:16
    container_name: awx_postgres
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
    volumes:
      - awx_postgres_data:/var/lib/postgresql/data
    networks:
      - awx_network

  awx_redis:
    image: redis:7
    container_name: awx_redis
    networks:
      - awx_network

  awx:
    image: quay.io/ansible/awx:23.6.0
    container_name: awx_web
    depends_on:
      - awx_postgres
      - awx_redis
    ports:
      - "80:8052"
    environment:
      SECRET_KEY: supersecretkey
      DATABASE_USER: awx
      DATABASE_PASSWORD: awxpass
      DATABASE_NAME: awx
      DATABASE_HOST: awx_postgres
      REDIS_HOST: awx_redis
      AWX_ADMIN_USER: admin
      AWX_ADMIN_PASSWORD: adminpass
    networks:
      - awx_network
    volumes:
      - awx_data:/var/lib/awx

volumes:
  awx_postgres_data:
  awx_data:

networks:
  awx_network: