apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: myapp-nginx
        image: nginx:latest
        ports:
        - containerPort: 80

#ESCALADO HORIZONTAL

#ESCALADO VERTICAL