services:
  # Servicio de MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password_123 # Contraseña del usuario root
      MYSQL_DATABASE: mi_database # Nombre de la base de datos inicial
      MYSQL_USER: mi_usuario # Usuario adicional
      MYSQL_PASSWORD: mi_password # Contraseña del usuario adicional
    ports:
      - "3306:3306" # Puerto expuesto: local:contenedor
    volumes:
      - mysql_data:/var/lib/mysql # Volumen para persistir los datos
    networks:
      - shared_network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

# Volúmenes
volumes:
  mysql_data:
    driver: local

# Redes
networks:
  shared_network:
    external: true
